---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: accounting
spec:
  podSelector:
    matchLabels:
      opentelemetry.io/name: accounting
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: kafka
    ports:
    - protocol: TCP
      port: 9092
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: postgresql
    ports:
    - protocol: TCP
      port: 5432