---
# Source: opentelemetry-demo/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-demo
  namespace: {{ .Values.namespace }}
  labels:
    
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/part-of: opentelemetry-demo