---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cart
spec:
  podSelector:
    matchLabels:
      opentelemetry.io/name: cart
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: frontend
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: checkout
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: valkey-cart
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: flagd
    ports:
    - protocol: TCP
      port: 8013
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: checkout
    ports:
    - protocol: TCP
      port: 8080
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53