---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: load-generator
spec:
  podSelector:
    matchLabels:
      opentelemetry.io/name: load-generator
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: frontend-proxy
    ports:
    - protocol: TCP
      port: 8080