---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argocd-image-updater
    targetRevision: 1.1.1
    helm:
      valueFiles:
      - $values/swan_kubernetes/swan_argocd/system/argocd-image-updater.yaml
  - repoURL: 'https://github.com/swanpyaetun/swan_polyglot-microservices-application.git'
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd