# Default values for frontend-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_opentelemetry-demo/frontend-proxy
  tag: "1e53ffac3d9b415702e7619857cf0f3b46c8d3cb"
swan_ingress:
  swan_host: www.swanpyaetun.com
  swan_acm_certificate_arn: arn:aws:acm:ap-southeast-1:655355946217:certificate/b4552389-3ef5-4c74-9f1d-70a087f6cc4f