---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fraud-detection
spec:
  podSelector:
    matchLabels:
      opentelemetry.io/name: fraud-detection
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: kafka
    ports:
    - protocol: TCP
      port: 9092
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: flagd
    ports:
    - protocol: TCP
      port: 8013