apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: microservices-image-updater
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: newest-build
  applicationRefs:
    - namePattern: "accounting"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/accounting/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/accounting
    - namePattern: "ad"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/ad/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/ad
    - namePattern: "cart"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/cart/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/cart
    - namePattern: "checkout"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/checkout/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/checkout
    - namePattern: "currency"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/currency/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/currency
    - namePattern: "email"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/email/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/email
    - namePattern: "flagd"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/flagd/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/flagd
    - namePattern: "fraud-detection"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/fraud-detection/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/fraud-detection
    - namePattern: "frontend"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/frontend/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/frontend
    - namePattern: "frontend-proxy"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/frontend-proxy/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/frontend-proxy
    - namePattern: "image-provider"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/image-provider/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/image-provider
    - namePattern: "kafka"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/kafka/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/kafka
    - namePattern: "llm"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/llm/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/llm
    - namePattern: "load-generator"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/load-generator/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/load-generator
    - namePattern: "payment"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/payment/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/payment
    - namePattern: "product-catalog"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/product-catalog/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/product-catalog
    - namePattern: "product-reviews"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/product-reviews/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/product-reviews
    - namePattern: "quote"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/quote/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/quote
    - namePattern: "recommendation"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/recommendation/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/recommendation
    - namePattern: "shipping"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/shipping/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/shipping