apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: microservices-image-updater
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: newest-build
  applicationRefs:
    - namePattern: "ad"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/ad/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/ad
    - namePattern: "cart"
      writeBackConfig:
        method: git
        gitConfig:
          repository: git@github.com:swanpyaetun/swan_polyglot-microservices-application.git
          branch: main
          writeBackTarget: helmvalues:swan_kubernetes/swan_helm/swan_microservices/cart/values.yaml
      images:
        - alias: image
          imageName: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/cart