---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-proxy
spec:
  podSelector:
    matchLabels:
      opentelemetry.io/name: frontend-proxy
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: flagd
    ports:
    - protocol: TCP
      port: 8013
    - protocol: TCP
      port: 4000
  - to:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: frontend
    ports:
    - protocol: TCP
      port: 8080
  - to:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: image-provider
    ports:
    - protocol: TCP
      port: 8081
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53