---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: checkout
spec:
  podSelector:
    matchLabels:
      opentelemetry.io/name: checkout
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: frontend
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: currency
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: cart
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: payment
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: email
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: product-catalog
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: shipping
    ports:
    - protocol: TCP
      port: 8080
  - to:
    - namespaceSelector:
        matchLabels:
          name: otel-demo
      podSelector:
        matchLabels:
          opentelemetry.io/name: kafka
    ports:
    - protocol: TCP
      port: 9092